name: "Setting up Node and install dependencies"
description: "Setup Node and install dependencies"
runs:
  using: "composite"
  steps:
    - name: "Check out repository code"
      uses: actions/checkout@v4

    - name: "Setup Node.js"
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - name: "Show Node & NPM version"
      shell: bash
      run: |
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"
    
    - name: "Install dependencies"
      shell: bash
      run: |
        echo "Installing dependencies..."
        npm ci
        echo "Dependencies installed."
